---
title: "Lead-IQ Project_01"
author: "Irena Frenkel"
date: "10/4/2032"
output: html_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, echo = FALSE, cache = TRUE}
#read in data
lead_dat <- read.csv("/Users/irenaf/Projects/Frenkel_Project_01/DataRaw/lead-iq-01.csv")
```

# IQ Levels by Location Status

```{r, include = FALSE}
#Create boxplot
boxplot(IQ ~ Smelter, data = lead_dat,
        xlab = "Location Status", ylab = "IQ Level",
        main = "Box Plot of IQ Level by Location",
        col = c("Purple", "Pink"), 
        names = c("Far", "Near"), 
        outline = TRUE,
        boxwex = 0.4,  # Adjust box width
        at = c(1, 2),   # Set positions for "Far" and "Near"
        ylim = c(0, 160))
```
```{r}
```

---

```{r, include = FALSE, echo = FALSE}
library(knitr)

# Calculate statistics for the 'Far' and 'Near' smelter groups
mean_far <- round(mean(lead_dat$IQ[lead_dat$Smelter == "Far"]),2)
mean_near <- round(mean(lead_dat$IQ[lead_dat$Smelter == "Near"]),2)
sd_far <- round(sd(lead_dat$IQ[lead_dat$Smelter == "Far"]),2)
sd_near <- round(sd(lead_dat$IQ[lead_dat$Smelter == "Near"]),2)
sample_size_far <- round(sum(lead_dat$Smelter == "Far"),2)
sample_size_near <- round(sum(lead_dat$Smelter == "Near"),2)

# Create a data frame for the statistics
tab <- data.frame(
  Smelter = c("Far", "Near"),
  SampleSize = c(sample_size_far, sample_size_near),
   Mean = c(mean_far, mean_near),
   SD = c(sd_far, sd_near)
)

#Create table

kable(tab, align ='lcrr', format = 'simple', col.names = c("Smelter","Sample Size", "Mean IQ", "Standard Deviation"),caption ="Summary Statistics by Smelter Location Status")
```

```{r, include = FALSE}
#The box plot and summary statistics table above shows children living far from the lead smelter had higher IQ levels. The boxplot shows that the far group had higher median IQ levels. The table shows that the far group has a mean IQ of 106.12 and the near group has a mean IQ of 89.19.
```
# Updated Graph

```{r, echo = FALSE}
# Update the incorrect IQ value
lead_dat$IQ[lead_dat$IQ == 999] <- 99

# Rerun code for Table and graph above and update text box

#Create boxplot
boxplot(IQ ~ Smelter, data = lead_dat,
        xlab = "Location Status", ylab = "IQ Level",
        main = "Box Plot of IQ Level by Location",
        col = c("Purple", "Pink"), 
        names = c("Far", "Near"), 
        outline = TRUE,
        boxwex = 0.4,  # Adjust box width
        at = c(1, 2),   # Set positions for "Far" and "Near"
        ylim = c(0, 160))

library(knitr)

# Calculate statistics for the 'Far' and 'Near' smelter groups
mean_far <- round(mean(lead_dat$IQ[lead_dat$Smelter == "Far"]),2)
mean_near <- round(mean(lead_dat$IQ[lead_dat$Smelter == "Near"]),2)
sd_far <- round(sd(lead_dat$IQ[lead_dat$Smelter == "Far"]),2)
sd_near <- round(sd(lead_dat$IQ[lead_dat$Smelter == "Near"]),2)
sample_size_far <- round(sum(lead_dat$Smelter == "Far"),2)
sample_size_near <- round(sum(lead_dat$Smelter == "Near"),2)

# Create a data frame for the statistics
tab <- data.frame(
  Smelter = c("Far", "Near"),
  SampleSize = c(sample_size_far, sample_size_near),
   Mean = c(mean_far, mean_near),
   SD = c(sd_far, sd_near)
)

#Create table
```

# Updated Table

```{r, echo = FALSE}
kable(tab, align ='lcrr', format = 'simple', col.names = c("Smelter","Sample Size", "Mean IQ", "Standard Deviation"),caption ="Summary Statistics by Smelter Location Status")
```

---

```{r}
#The box plot and summary statistics table above shows children living far from the lead smelter had higher IQ levels. The boxplot shows that the far group had higher median IQ levels. The table shows that the far group has a mean IQ of 92.69 and the near group has a mean IQ of 89.19.
```


